/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  VgSelectOption,
} from './components/vg-select/types';


export namespace Components {

  interface MyComponent {}
  interface MyComponentAttributes extends StencilHTMLAttributes {}

  interface VgSelect {
    'clearable': boolean;
    'error': string;
    'handleSelect': Function;
    'initialValue': string;
    'multiple': boolean;
    'options': VgSelectOption[];
    'placeholder': string;
    'searchable': boolean;
    'value': string | number | string[] | number[];
  }
  interface VgSelectAttributes extends StencilHTMLAttributes {
    'clearable'?: boolean;
    'error'?: string;
    'handleSelect'?: Function;
    'initialValue'?: string;
    'multiple'?: boolean;
    'options'?: VgSelectOption[];
    'placeholder'?: string;
    'searchable'?: boolean;
    'value'?: string | number | string[] | number[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'VgSelect': Components.VgSelect;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'vg-select': Components.VgSelectAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLVgSelectElement extends Components.VgSelect, HTMLStencilElement {}
  var HTMLVgSelectElement: {
    prototype: HTMLVgSelectElement;
    new (): HTMLVgSelectElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'vg-select': HTMLVgSelectElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'vg-select': HTMLVgSelectElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
